import React from 'react';
import { Card, CardHeader, CardTitle, CardContent } from './ui/Card';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';
import { AnalysisResult } from '@/lib/types';

interface SimulationChartProps {
    simulationData: { date: string; value: number }[]; // array of simulated portfolio values over time
}

/**
 * SimulationChart displays a line chart of Monte Carlo simulation results.
 * It expects an array of objects with a date (or step) and a numeric value.
 * In a real app, this data would be generated by the backend simulation service.
 */
export const SimulationChart: React.FC<SimulationChartProps> = ({ simulationData }) => {
    return (
        <Card>
            <CardHeader>
                <CardTitle className="font-serif text-primary">Monte Carlo Simulation Trajectory</CardTitle>
            </CardHeader>
            <CardContent className="h-[300px]">
                <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={simulationData} margin={{ top: 5, right: 20, left: 10, bottom: 5 }}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                        <XAxis
                            dataKey="date"
                            tick={{ fontSize: 12, fill: '#6b7280' }}
                            stroke="#9ca3af"
                        />
                        <YAxis
                            tick={{ fontSize: 12, fill: '#6b7280' }}
                            stroke="#9ca3af"
                            tickFormatter={(value) => `$${value.toFixed(0)}`}
                        />
                        <Tooltip
                            contentStyle={{
                                backgroundColor: '#fff',
                                borderColor: '#e5e7eb',
                                borderRadius: '0.5rem',
                                color: '#1f2937'
                            }}
                            itemStyle={{ color: '#004185' }}
                            formatter={(value: number) => [`$${value.toFixed(2)}`, 'Portfolio Value']}
                        />
                        <Line
                            type="monotone"
                            dataKey="value"
                            stroke="#004185"
                            strokeWidth={3}
                            dot={false}
                            activeDot={{ r: 6, fill: '#004185' }}
                        />
                    </LineChart>
                </ResponsiveContainer>
            </CardContent>
        </Card>
    );
};
